apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: general
spec:
  amiFamily: Bottlerocket
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: cs3219-eks
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: cs3219-eks
  instanceProfile: cs3219-eks-karpenter-node
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general
spec:
  template:
    spec:
      nodeClassRef:
        name: general
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        # prioritize spot instances to save costs, fallback on on-demand instances
        values: ["spot", "on-demand"]
      - key: "node.kubernetes.io/instance-type"
        operator: In
        # prioritize spot instances of these amd64 instance types
        values: ["t3.medium","t3.large","t3a.medium","t3a.large"] 
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
  limits:
    # Limited at 2 nodes
    cpu: "4"
    memory: "8Gi"
  disruption:
    expireAfter: "720h"
    consolidateAfter: "2m"