# Example secrets file - DO NOT USE IN PRODUCTION
# Copy this file and fill in actual values (DO NOT COMMIT THE COPY)

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: cs3219
type: Opaque
stringData:
  # Question DB credentials
  question-db-user: "questionuser"
  question-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  question-db-name: "questiondb"
  
  # User DB credentials
  user-db-user: "user"
  user-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  user-db-name: "userdb"
  
  # Collaboration DB credentials
  collab-db-user: "collabuser"
  collab-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  collab-db-name: "collabdb"
  
  # Redis password (optional, leave empty for no auth in dev)
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cs3219
type: Opaque
stringData:
  # User service JWT secrets
  jwt-secret: "REPLACE_WITH_STRONG_SECRET_64_CHARS_MIN"
  # RSA keypair used for RS256 JWT signing and JWKS exposure
  rsa-private-key: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_BASE64_PKCS8_PRIVATE_KEY
    -----END PRIVATE KEY-----
  rsa-public-key: |
    -----BEGIN PUBLIC KEY-----
    REPLACE_WITH_SPKI_PUBLIC_KEY
    -----END PUBLIC KEY-----
  # Public JWKS URL exposed by user-service (must be externally reachable)
  jwks-uri: "https://your-domain.com/api/v1/.well-known/jwks.json"
  google-client-id: "your-google-oauth-client-id.apps.googleusercontent.com"
  google-client-secret: "your-google-oauth-client-secret"
  google-redirect-uri: "https://your-domain.com/api/v1/auth/google/callback"
  # Frontend URLs used by auth controller to redirect after success/error
  web-callback-url: "https://your-domain.com/auth/callback"
  web-error-url: "https://your-domain.com/auth/error"
  # Judge0 API (optional)
  judge0-auth-token: ""
