# Example secrets file - DO NOT USE IN PRODUCTION
# Copy this file and fill in actual values (DO NOT COMMIT THE COPY)

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: cs3219
type: Opaque
stringData:
  # Question DB credentials
  question-db-user: "questionuser"
  question-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  question-db-name: "questiondb"
  
  # User DB credentials
  user-db-user: "user"
  user-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  user-db-name: "userdb"
  
  # Collaboration DB credentials
  collab-db-user: "collabuser"
  collab-db-password: "REPLACE_WITH_STRONG_PASSWORD"
  collab-db-name: "collabdb"
  
  # Redis password (optional, leave empty for no auth in dev)
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: cs3219
type: Opaque
stringData:
  # User service JWT secrets
  jwt-secret: "REPLACE_WITH_STRONG_SECRET_64_CHARS_MIN"
  google-client-id: "your-google-oauth-client-id.apps.googleusercontent.com"
  google-client-secret: "your-google-oauth-client-secret"
  google-callback-url: "https://your-domain.com/v1/auth/google/callback"
