name: DEPRECATED: Build and Push to GHCR (disabled)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated notice
        run: |
          echo "This workflow is deprecated. Use 'Build Images (no push)' for CI and 'Push Images to GHCR (manual)' to publish images."
