name: CI

on:
  pull_request:
    branches: ["master", "main"]
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODEOWNERS'
      - 'docs/**'
      - 'infra/**'
  push:
    branches: ["master", "main"]
    paths-ignore:
      - '**/*.md'
      - '**/*.MD'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/CODEOWNERS'
      - 'docs/**'
      - 'infra/**'
  workflow_dispatch: {}
 
jobs:
  # TODO: update to build/test based on FE/microservice to avoid excessively long CI
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
 
      - uses: pnpm/action-setup@v3
        with:
          version: 8
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
 
      - name: Install dependencies
        run: pnpm install
 
      - name: Build
        run: pnpm build
 
      - name: Test
        run: pnpm test
